# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QSpinBox, QStackedWidget, QStatusBar, QTableView,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(804, 581)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 801, 511))
        self.income_expense = QWidget()
        self.income_expense.setObjectName(u"income_expense")
        self.amount_label = QLabel(self.income_expense)
        self.amount_label.setObjectName(u"amount_label")
        self.amount_label.setGeometry(QRect(30, 90, 111, 21))
        self.add_record_button = QPushButton(self.income_expense)
        self.add_record_button.setObjectName(u"add_record_button")
        self.add_record_button.setGeometry(QRect(20, 460, 131, 32))
        self.necessity_label = QLabel(self.income_expense)
        self.necessity_label.setObjectName(u"necessity_label")
        self.necessity_label.setGeometry(QRect(30, 330, 71, 21))
        self.date_label = QLabel(self.income_expense)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(30, 250, 58, 16))
        self.bank_label = QLabel(self.income_expense)
        self.bank_label.setObjectName(u"bank_label")
        self.bank_label.setGeometry(QRect(30, 170, 58, 21))
        self.bank_choose_field = QComboBox(self.income_expense)
        self.bank_choose_field.setObjectName(u"bank_choose_field")
        self.bank_choose_field.setGeometry(QRect(140, 170, 91, 21))
        self.amount_entry_field = QLineEdit(self.income_expense)
        self.amount_entry_field.setObjectName(u"amount_entry_field")
        self.amount_entry_field.setGeometry(QRect(140, 90, 91, 21))
        self.date_selector_income_expense = QDateEdit(self.income_expense)
        self.date_selector_income_expense.setObjectName(u"date_selector_income_expense")
        self.date_selector_income_expense.setGeometry(QRect(140, 250, 91, 22))
        self.date_selector_income_expense.setCalendarPopup(True)
        self.sql_tableview = QTableView(self.income_expense)
        self.sql_tableview.setObjectName(u"sql_tableview")
        self.sql_tableview.setGeometry(QRect(400, 60, 351, 371))
        self.necessity_choose_field = QComboBox(self.income_expense)
        self.necessity_choose_field.addItem("")
        self.necessity_choose_field.addItem("")
        self.necessity_choose_field.setObjectName(u"necessity_choose_field")
        self.necessity_choose_field.setGeometry(QRect(140, 330, 91, 21))
        self.back_to_summary_income_expense_button = QPushButton(self.income_expense)
        self.back_to_summary_income_expense_button.setObjectName(u"back_to_summary_income_expense_button")
        self.back_to_summary_income_expense_button.setGeometry(QRect(620, 460, 131, 32))
        self.delete_record_income_expense_button = QPushButton(self.income_expense)
        self.delete_record_income_expense_button.setObjectName(u"delete_record_income_expense_button")
        self.delete_record_income_expense_button.setGeometry(QRect(200, 460, 131, 32))
        self.stackedWidget.addWidget(self.income_expense)
        self.bank_account = QWidget()
        self.bank_account.setObjectName(u"bank_account")
        self.apr_label = QLabel(self.bank_account)
        self.apr_label.setObjectName(u"apr_label")
        self.apr_label.setGeometry(QRect(40, 290, 81, 16))
        self.date_label_2 = QLabel(self.bank_account)
        self.date_label_2.setObjectName(u"date_label_2")
        self.date_label_2.setGeometry(QRect(40, 170, 58, 16))
        self.deposit_amount_label = QLabel(self.bank_account)
        self.deposit_amount_label.setObjectName(u"deposit_amount_label")
        self.deposit_amount_label.setGeometry(QRect(40, 110, 111, 16))
        self.update_balances_button = QPushButton(self.bank_account)
        self.update_balances_button.setObjectName(u"update_balances_button")
        self.update_balances_button.setGeometry(QRect(400, 470, 121, 32))
        self.gets_apr_label = QLabel(self.bank_account)
        self.gets_apr_label.setObjectName(u"gets_apr_label")
        self.gets_apr_label.setGeometry(QRect(40, 230, 71, 16))
        self.bank_name_entry_field = QLineEdit(self.bank_account)
        self.bank_name_entry_field.setObjectName(u"bank_name_entry_field")
        self.bank_name_entry_field.setGeometry(QRect(170, 50, 113, 21))
        self.apr_choose_field = QComboBox(self.bank_account)
        self.apr_choose_field.addItem("")
        self.apr_choose_field.addItem("")
        self.apr_choose_field.setObjectName(u"apr_choose_field")
        self.apr_choose_field.setGeometry(QRect(170, 340, 91, 21))
        self.apr_type_label = QLabel(self.bank_account)
        self.apr_type_label.setObjectName(u"apr_type_label")
        self.apr_type_label.setGeometry(QRect(40, 350, 71, 16))
        self.deposit_amount_entry_field = QLineEdit(self.bank_account)
        self.deposit_amount_entry_field.setObjectName(u"deposit_amount_entry_field")
        self.deposit_amount_entry_field.setGeometry(QRect(170, 110, 113, 21))
        self.days_label = QLabel(self.bank_account)
        self.days_label.setObjectName(u"days_label")
        self.days_label.setGeometry(QRect(40, 410, 58, 16))
        self.days_spinbox = QSpinBox(self.bank_account)
        self.days_spinbox.setObjectName(u"days_spinbox")
        self.days_spinbox.setGeometry(QRect(170, 410, 91, 22))
        self.days_spinbox.setMaximum(365)
        self.add_bank_button = QPushButton(self.bank_account)
        self.add_bank_button.setObjectName(u"add_bank_button")
        self.add_bank_button.setGeometry(QRect(30, 470, 131, 32))
        self.date_selector_bank = QDateEdit(self.bank_account)
        self.date_selector_bank.setObjectName(u"date_selector_bank")
        self.date_selector_bank.setGeometry(QRect(170, 170, 111, 22))
        self.date_selector_bank.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.date_selector_bank.setCalendarPopup(True)
        self.bank_name_label = QLabel(self.bank_account)
        self.bank_name_label.setObjectName(u"bank_name_label")
        self.bank_name_label.setGeometry(QRect(40, 50, 81, 16))
        self.bank_account_tableView = QTableView(self.bank_account)
        self.bank_account_tableView.setObjectName(u"bank_account_tableView")
        self.bank_account_tableView.setGeometry(QRect(400, 50, 321, 401))
        self.apr_rate_entry_field = QLineEdit(self.bank_account)
        self.apr_rate_entry_field.setObjectName(u"apr_rate_entry_field")
        self.apr_rate_entry_field.setGeometry(QRect(170, 290, 91, 21))
        self.back_to_summary_bank_account_button = QPushButton(self.bank_account)
        self.back_to_summary_bank_account_button.setObjectName(u"back_to_summary_bank_account_button")
        self.back_to_summary_bank_account_button.setGeometry(QRect(590, 470, 131, 32))
        self.gets_apr_group = QGroupBox(self.bank_account)
        self.gets_apr_group.setObjectName(u"gets_apr_group")
        self.gets_apr_group.setGeometry(QRect(170, 220, 111, 41))
        self.gets_apr_group.setStyleSheet(u"QGroupBox {\n"
"    border: none;\n"
"}")
        self.yesradio = QRadioButton(self.gets_apr_group)
        self.yesradio.setObjectName(u"yesradio")
        self.yesradio.setGeometry(QRect(0, 10, 51, 16))
        self.yesradio.setChecked(False)
        self.noradio = QRadioButton(self.gets_apr_group)
        self.noradio.setObjectName(u"noradio")
        self.noradio.setGeometry(QRect(60, 10, 51, 16))
        self.noradio.setChecked(True)
        self.delete_record_bank_button = QPushButton(self.bank_account)
        self.delete_record_bank_button.setObjectName(u"delete_record_bank_button")
        self.delete_record_bank_button.setGeometry(QRect(200, 470, 131, 32))
        self.stackedWidget.addWidget(self.bank_account)
        self.summary = QWidget()
        self.summary.setObjectName(u"summary")
        self.summary_label = QLabel(self.summary)
        self.summary_label.setObjectName(u"summary_label")
        self.summary_label.setGeometry(QRect(300, 50, 221, 91))
        font = QFont()
        font.setFamilies([u"Arial Rounded MT Bold"])
        font.setPointSize(36)
        font.setBold(False)
        self.summary_label.setFont(font)
        self.summary_label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.summary_label.setStyleSheet(u"")
        self.summary_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.summary_container = QWidget(self.summary)
        self.summary_container.setObjectName(u"summary_container")
        self.summary_container.setGeometry(QRect(40, 160, 721, 271))
        self.total_necessary_spending_box = QWidget(self.summary_container)
        self.total_necessary_spending_box.setObjectName(u"total_necessary_spending_box")
        self.total_necessary_spending_box.setGeometry(QRect(30, 0, 151, 271))
        self.total_necessary_spending_box.setStyleSheet(u"QWidget { background-color: rgba(210, 255, 210, 180); \n"
"border: 1px solid rgba(120, 200, 120, 200); \n"
"border-radius: 8px; } \n"
"")
        self.total_necessary_spending_label = QLabel(self.total_necessary_spending_box)
        self.total_necessary_spending_label.setObjectName(u"total_necessary_spending_label")
        self.total_necessary_spending_label.setGeometry(QRect(10, 30, 131, 101))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(12)
        font1.setWeight(QFont.DemiBold)
        self.total_necessary_spending_label.setFont(font1)
        self.total_necessary_spending_label.setStyleSheet(u"QLabel {\n"
"    color: #2E7D32;\n"
"}")
        self.total_necessary_spending_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_necessary_spending_number_output = QLabel(self.total_necessary_spending_box)
        self.total_necessary_spending_number_output.setObjectName(u"total_necessary_spending_number_output")
        self.total_necessary_spending_number_output.setGeometry(QRect(0, 189, 151, 41))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.total_necessary_spending_number_output.setFont(font2)
        self.total_necessary_spending_number_output.setStyleSheet(u"QLabel {\n"
"    color: #1B5E20;\n"
"}")
        self.total_necessary_spending_number_output.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_unnecessary_spending_box = QWidget(self.summary_container)
        self.total_unnecessary_spending_box.setObjectName(u"total_unnecessary_spending_box")
        self.total_unnecessary_spending_box.setGeometry(QRect(200, 0, 161, 271))
        self.total_unnecessary_spending_box.setStyleSheet(u"QWidget { background-color: rgba(255, 220, 220, 180); \n"
"border: 1px solid rgba(220, 150, 150, 200); \n"
"border-radius: 8px; } \n"
"")
        self.total_unnecessary_spendingnumber_holder = QLabel(self.total_unnecessary_spending_box)
        self.total_unnecessary_spendingnumber_holder.setObjectName(u"total_unnecessary_spendingnumber_holder")
        self.total_unnecessary_spendingnumber_holder.setGeometry(QRect(0, 190, 161, 41))
        self.total_unnecessary_spendingnumber_holder.setFont(font2)
        self.total_unnecessary_spendingnumber_holder.setStyleSheet(u"QLabel {\n"
"    color: #C62828;\n"
"}")
        self.total_unnecessary_spendingnumber_holder.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_unnecessary_spending_label = QLabel(self.total_unnecessary_spending_box)
        self.total_unnecessary_spending_label.setObjectName(u"total_unnecessary_spending_label")
        self.total_unnecessary_spending_label.setGeometry(QRect(10, 30, 141, 101))
        self.total_unnecessary_spending_label.setFont(font1)
        self.total_unnecessary_spending_label.setStyleSheet(u"QLabel {\n"
"    color: #B71C1C;\n"
"}")
        self.total_unnecessary_spending_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_revenue_box = QWidget(self.summary_container)
        self.total_revenue_box.setObjectName(u"total_revenue_box")
        self.total_revenue_box.setGeometry(QRect(380, 0, 161, 271))
        self.total_revenue_box.setStyleSheet(u"QWidget { background-color: rgba(210, 235, 255, 180); \n"
"border: 1px solid rgba(140, 180, 220, 200);\n"
"border-radius: 8px; } \n"
"")
        self.total_revenue_number_output = QLabel(self.total_revenue_box)
        self.total_revenue_number_output.setObjectName(u"total_revenue_number_output")
        self.total_revenue_number_output.setGeometry(QRect(0, 189, 161, 41))
        self.total_revenue_number_output.setFont(font2)
        self.total_revenue_number_output.setStyleSheet(u"QLabel {\n"
"    color: #0D47A1;\n"
"}")
        self.total_revenue_number_output.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_revenue_label = QLabel(self.total_revenue_box)
        self.total_revenue_label.setObjectName(u"total_revenue_label")
        self.total_revenue_label.setGeometry(QRect(10, 30, 141, 101))
        self.total_revenue_label.setFont(font1)
        self.total_revenue_label.setStyleSheet(u"QLabel {\n"
"    color: #1565C0;\n"
"}")
        self.total_revenue_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_spending_box = QWidget(self.summary_container)
        self.total_spending_box.setObjectName(u"total_spending_box")
        self.total_spending_box.setGeometry(QRect(560, 0, 161, 271))
        self.total_spending_box.setStyleSheet(u"QWidget { background-color: rgba(240, 240, 240, 170); \n"
"border: 1px solid rgba(200, 200, 200, 200); \n"
"border-radius: 8px; } \n"
"")
        self.total_spending_number_holder = QLabel(self.total_spending_box)
        self.total_spending_number_holder.setObjectName(u"total_spending_number_holder")
        self.total_spending_number_holder.setGeometry(QRect(0, 189, 161, 41))
        self.total_spending_number_holder.setFont(font2)
        self.total_spending_number_holder.setStyleSheet(u"QLabel {\n"
"    color: #212121;\n"
"}")
        self.total_spending_number_holder.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_spending_label = QLabel(self.total_spending_box)
        self.total_spending_label.setObjectName(u"total_spending_label")
        self.total_spending_label.setGeometry(QRect(10, 30, 141, 101))
        self.total_spending_label.setFont(font1)
        self.total_spending_label.setStyleSheet(u"QLabel {\n"
"    color: #424242;\n"
"}")
        self.total_spending_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.add_income_expense_button = QPushButton(self.summary)
        self.add_income_expense_button.setObjectName(u"add_income_expense_button")
        self.add_income_expense_button.setGeometry(QRect(500, 480, 151, 32))
        self.add_bank_account_button = QPushButton(self.summary)
        self.add_bank_account_button.setObjectName(u"add_bank_account_button")
        self.add_bank_account_button.setGeometry(QRect(170, 480, 151, 32))
        self.stackedWidget.addWidget(self.summary)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 804, 38))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Expense Tracker", None))
#if QT_CONFIG(tooltip)
        self.stackedWidget.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.amount_label.setText(QCoreApplication.translate("MainWindow", u"Amount:", None))
        self.add_record_button.setText(QCoreApplication.translate("MainWindow", u"Add Record", None))
        self.necessity_label.setText(QCoreApplication.translate("MainWindow", u"Necessity:", None))
        self.date_label.setText(QCoreApplication.translate("MainWindow", u"Date:", None))
        self.bank_label.setText(QCoreApplication.translate("MainWindow", u"Bank:", None))
        self.bank_choose_field.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.amount_entry_field.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.amount_entry_field.setInputMask("")
        self.amount_entry_field.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Toman", None))
        self.date_selector_income_expense.setDisplayFormat(QCoreApplication.translate("MainWindow", u"M/d/yyyy", None))
        self.necessity_choose_field.setItemText(0, QCoreApplication.translate("MainWindow", u"Yes", None))
        self.necessity_choose_field.setItemText(1, QCoreApplication.translate("MainWindow", u"No", None))

        self.back_to_summary_income_expense_button.setText(QCoreApplication.translate("MainWindow", u"Back To Summary", None))
        self.delete_record_income_expense_button.setText(QCoreApplication.translate("MainWindow", u"Delete Record", None))
        self.apr_label.setText(QCoreApplication.translate("MainWindow", u"APR Rate:", None))
        self.date_label_2.setText(QCoreApplication.translate("MainWindow", u"Date:", None))
        self.deposit_amount_label.setText(QCoreApplication.translate("MainWindow", u"Deposit Amount:", None))
        self.update_balances_button.setText(QCoreApplication.translate("MainWindow", u"Update Balances", None))
        self.gets_apr_label.setText(QCoreApplication.translate("MainWindow", u"Gets APR?", None))
        self.bank_name_entry_field.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Melli, Mellat, Blu, etc..", None))
        self.apr_choose_field.setItemText(0, QCoreApplication.translate("MainWindow", u"Monthly", None))
        self.apr_choose_field.setItemText(1, QCoreApplication.translate("MainWindow", u"Annually", None))

        self.apr_choose_field.setPlaceholderText("")
        self.apr_type_label.setText(QCoreApplication.translate("MainWindow", u"APR Type:", None))
#if QT_CONFIG(tooltip)
        self.deposit_amount_entry_field.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.deposit_amount_entry_field.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Toman", None))
        self.days_label.setText(QCoreApplication.translate("MainWindow", u"Days:", None))
        self.add_bank_button.setText(QCoreApplication.translate("MainWindow", u"Add Bank", None))
        self.date_selector_bank.setDisplayFormat(QCoreApplication.translate("MainWindow", u"M/d/yyyy", None))
        self.bank_name_label.setText(QCoreApplication.translate("MainWindow", u"Bank Name:", None))
        self.apr_rate_entry_field.setPlaceholderText(QCoreApplication.translate("MainWindow", u"5", None))
        self.back_to_summary_bank_account_button.setText(QCoreApplication.translate("MainWindow", u"Back to Summary", None))
        self.gets_apr_group.setTitle("")
        self.yesradio.setText(QCoreApplication.translate("MainWindow", u"yes", None))
        self.noradio.setText(QCoreApplication.translate("MainWindow", u"no", None))
        self.delete_record_bank_button.setText(QCoreApplication.translate("MainWindow", u"Delete Record", None))
        self.summary_label.setText(QCoreApplication.translate("MainWindow", u"Summary", None))
        self.total_necessary_spending_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Total </p><p>Necessary </p><p>Spending</p></body></html>", None))
        self.total_necessary_spending_number_output.setText(QCoreApplication.translate("MainWindow", u"$0.00 (PlaceHolder)", None))
        self.total_unnecessary_spendingnumber_holder.setText(QCoreApplication.translate("MainWindow", u"$0.00 (PlaceHolder)", None))
        self.total_unnecessary_spending_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Total </p><p>Unnecessary </p><p>Spending</p></body></html>", None))
        self.total_revenue_number_output.setText(QCoreApplication.translate("MainWindow", u"$0.00 (PlaceHolder)", None))
        self.total_revenue_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Total </p><p>Revenue</p></body></html>", None))
        self.total_spending_number_holder.setText(QCoreApplication.translate("MainWindow", u"$0.00 (PlaceHolder)", None))
        self.total_spending_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Total</p><p>Spending</p></body></html>", None))
        self.add_income_expense_button.setText(QCoreApplication.translate("MainWindow", u"Add Income/Expense", None))
        self.add_bank_account_button.setText(QCoreApplication.translate("MainWindow", u"Add Bank Account", None))
    # retranslateUi

